### PR TITLE
Install zeekctl into Zeek's common Python library subdirectory

### PR DESCRIPTION
**Pull request by ckreibich**
The old hardwired installation location is removed if still present.

Companion PR to zeek/zeek#1290, which will pull in these changes.

### CODE REVIEW

**Comment by 0xxon** [comment]
One small question - would it be hard to check that there are no unexpected files in the old installation location?

Removing existing files always makes me a tad nervous.

**Comment by ckreibich** [comment]
Yeah, good point ... @rsmmr and I just discussed and landed on removing only the files we know are zeekctl's, while leaving anything else in place. I like that a lot, seems much more in line with what package managers also do. I'll give that a shot, and I'm also looking at that CI problem.

**Comment by ckreibich** [comment]
> Removing existing files always makes me a tad nervous.

Heheeee ... good instinct. It's why CI fails — it's running with a master-branch Zeek, which doesn't yet know about the new `python` directory, and so still has the Broker Python bindings installed in the old `zeekctl` directory, which the removal blows away, and so the bindings aren't found.

I'll make another pass over this.

**Comment by 0xxon** [comment]
I know this is potentially a bit late - but I just had another thought about this.

There are some people that try to install Zeek in a way that is more like default linux installations - so in /usr/local, or just /usr. This makes the libraries end up in /usr/lib and /usr/local/lib. 

This new change will mean that the python libraries end up in /usr/lib/python in this case - with no way to easily override that, right?

If that is the case that feels a tiny bit icky again :)

**Pull request merged**
