### PR TITLE
Move ZeekPort out of Linux's ephemeral port range (47760 to 27760)

### PR DESCRIPTION
**Pull request by awelzel**
WARNING: This breaks users that have setup strict firewalls between Zeek
         nodes, but at the same time fixes spurious worker failures.

On Linux, port 47760 and the following ports selected by zeekctl fall square
into the ephemeral port range. This has resulted in multiple users reporting
Zeek workers spuriously failing to start with messages as follows:

    error in /usr/local/zeek-5.0.0/share/zeek/base/frameworks/cluster/./setup-connections.zeek, lines 94-96: Failed to listen on INADDR_ANY:47764 (Broker::listen(Broker::default_listen_address, Cluster::self$p, Broker::default_listen_retry))
    fatal error: errors occurred while initializing

This can happen when another process on the system are using a port that
a Zeek process is supposed to listen on. They are free to do so, these
ports are in the default ephemeral port range. Even the outgoing connection
from the same or another worker to the manager or logger has been
observed to cause this.

FreeBSD users have not seen this previously, as its ephemeral port range
is above 47760 (49152), but on Linux it starts as low as 32768.

### CODE REVIEW

**Comment by m1357** [comment]
Setting ZeekPort = 27760 in zeekctl.cfg and redeploying cluster with proper firewall rules allows cluster to start with no failed worker socket binds.

**Comment by Canon88** [comment]
It seems to be working, but there are still 5 workers that show a status of "crashed" at startup. I think it's because the ports are still occupied at the moment of startup, I'll let it run for a while and I'll continue to give feedback next week.

**Comment by ckreibich** [comment]
@Canon88, have you learned anything else? I'm in favor of merging Arne's changes, with a heads-up in `NEWS`.

**Review by ckreibich — APPROVED** [review]

**Comment by timwoj** [comment]
@Canon88 one more quick ping to see if you were still having problems. I'm inclined to merge this as-is and update zeek master, but not bring in into the upcoming 5.1 release. The reasoning for not including it is that it's likely to causing routing/firewall changes and we want to give users some warning that that's happening first.

**Comment by timwoj** [comment]
Merged, and added into zeek `master` with a NEWS entry.

**Pull request merged**
